services:
  app:
    build: .
    depends_on:
      pgvector:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgvector:5432/sophia_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 12345


  pgvector:
    image: pgvector/pgvector:pg17-trixie
    restart: always
    environment:
      POSTGRES_DB: sophia_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d sophia_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
